# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-09 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compareword',
            name='origin',
            field=models.FileField(blank=True, null=True, upload_to='manuel/%Y/%m/d'),
        ),
    ]
