# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-09 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0002_auto_20180109_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compareword',
            name='origin',
            field=models.FileField(blank=True, null=True, upload_to='manual/%Y/%m/%d'),
        ),
    ]
