# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-10 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0004_auto_20180109_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='worddict',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
