# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-28 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0005_worddict_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compareword',
            name='result',
            field=models.TextField(),
        ),
    ]
