# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-15 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0006_auto_20180228_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='worddict',
            name='word_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
